### PR TITLE
Added TriggerSF with 3 electron Triggers

### PR DESCRIPTION
**Pull request by mafrahm**

### CODE REVIEW

**Comment by reimersa** [comment]
Das BTagEfficiency file bitte nicht mit in den TriggerSF Ordner.

**Comment by reimersa** [comment]
I don't see the corresponding new files for 2018, are they still coming?

**Comment by reimersa** [comment]
Have you moved back the BTagEfficiency rootfile for 2016?

**Comment by mafrahm** [comment]
I only copied it to begin with, so, yes, it's still there

**Pull request merged**
